"""empty message

Revision ID: 242a4eaacd62
Revises: 988cd8f8b925
Create Date: 2020-11-27 12:35:33.819717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242a4eaacd62'
down_revision = '988cd8f8b925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('topicdescription', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'transaction', 'guest', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('topics', 'topicdescription')
    # ### end Alembic commands ###
