"""empty message

Revision ID: 988cd8f8b925
Revises: f39a442be0da
Create Date: 2020-11-27 12:25:26.286397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988cd8f8b925'
down_revision = 'f39a442be0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'guest', 'state', ['guest_state'], ['state_id'])
    op.create_foreign_key(None, 'transaction', 'guest', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'guest', type_='foreignkey')
    # ### end Alembic commands ###
