"""empty message

Revision ID: f39a442be0da
Revises: 2dff2924ed53
Create Date: 2020-11-27 12:24:57.090091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39a442be0da'
down_revision = '2dff2924ed53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('topicid', sa.Integer(), nullable=False),
    sa.Column('topicname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('topicid')
    )
    op.create_foreign_key(None, 'guest', 'state', ['guest_state'], ['state_id'])
    op.create_foreign_key(None, 'transaction', 'guest', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.drop_table('topics')
    # ### end Alembic commands ###
